spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
  security:
    filter:
      dispatcher-types: REQUEST,FORWARD,ASYNC
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  common:
    app:
      idm-url: http://localhost:8080/flowable/
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: admin
        last-name: admin
  rest:
    app:
      authentication-mode: verify-privilege
  modeler:
    app:
      rest-enabled: true
  database-schema-update: false
  #配置
  activityFontName: \u5B8B\u4F53
  labelFontName: \u5B8B\u4F53
  annotationFontName: \u5B8B\u4F53

mybatis:
  mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
  typeAliasesPackage: com.javatest.flowable.po
  config-location: classpath:/META-INF/mybatis-config.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
#    map-underscore-to-camel-case: true       #开启mybatis驼峰命名转换
server:
  port: 8181
  servlet:
    context-path: /flowable
logging:
  level:
    com.javatest.flowable: debug